In [9]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
# NumPy massivlarini ishga tushirish usullaridan biri Python roʻyxatlaridan ikki
# yoki undan yuqori oʻlchamli maʼlumotlar uchun ichki roʻyxatlardan foydalanishdir.

In [11]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
print(a[0])


[1 2 3 4]


In [21]:
s = np.zeros(2)
s

array([0., 0.])

In [15]:
s = np.ones(2)
s

array([1., 1.])

In [17]:
a = np.empty(2) 
a

array([1., 1.])

In [18]:
s = np.arange(4)
s

array([0, 1, 2, 3])

In [ ]:
# np.linspace() Belgilangan oraliqda chiziqli ravishda joylashtirilgan qiymatlar
# bilan massiv yaratish uchun ham foydalanishingiz mumkin

In [19]:
s = np.linspace(0, 10, num=5)
s

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# Elementlarni qo'shish, o'chirish va saralash 


In [20]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [22]:
num = np.sort(arr)
num

array([1, 2, 3, 4, 5, 6, 7, 8])